export AWS_ACCESS_KEY_ID=<access_key>
export AWS_SECRET_ACCESS_KEY=<access_key>

SCRIPTS_DIR_INFRA_DOCKER=~/git/dev-ops-common/scripts/docker
SCRIPTS_DIR_INFRA_GLOBAL=~/git/dev-ops-common/scripts
SCRIPTS_DIR_INFRA_DEV_ENV=~/git/dev-ops-common/dev-env/scripts
SCRIPTS_DIR_SITE_JARCH=~/git/site-joe-rice-architect/devops/scripts
SCRIPTS_DIR_APP_MINECAT=~/git/app-mine-the-catalog/devops/scripts

export PATH=$PATH:$SCRIPTS_DIR_SITE_JARCH:$SCRIPTS_DIR_APP_MINECAT:$SCRIPTS_DIR_INFRA_DOCKER:$SCRIPTS_DIR_INFRA_GLOBAL:$SCRIPTS_DIR_INFRA_DEV_ENV