export SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"

export INFRA_MODULES_HOME_DIR=$SCRIPTS_DIR/../infra-modules
export INFRA_ENVIRONMENTS_HOME_DIR=$SCRIPTS_DIR/../environments

export INFRA_MODULES_DOCKER_SWARM_DIR=$INFRA_MODULES_HOME_DIR/docker-swarm-infra
export INFRA_MODULES_DOCKER_SWARM_ANSIBLE_DIR=$INFRA_MODULES_DOCKER_SWARM_DIR/ansible

export INFRA_MODULES_LOGGING_DIR=$INFRA_MODULES_HOME_DIR/infra-central-logging
export INFRA_MODULES_LOGGING_ANSIBLE_DIR=$INFRA_MODULES_LOGGING_DIR/ansible
export INFRA_MODULES_LOGGING_DOCKER_DIR=$INFRA_MODULES_LOGGING_DIR/docker

export LOGGING_SERVER_CODE_DIR=$INFRA_MODULES_HOME_DIR/centralized-logging-efk
export NGINX_PROXY_CODE_DIR=$INFRA_MODULES_HOME_DIR/centralized-logging-efk


export MACHINE_NAME_LOGGING_SERVER=infra-logging-server
export MACHINE_NAME_CI=infra-ci-server

export JRA_BUILD_PRIVATE_KEY_FILE='/home/vagrant/share/aws-keys/jra-build.pem'


export INFRA_LOGGING_FLUENTD_ES_NAMESPACE=joericearchitect
export INFRA_LOGGING_FLUENTD_ES_IMAGE_NAME=jarch-infra-logging-fluentd
export INFRA_LOGGING_FLUENTD_ES_CONTAINER_NAME=jarch-infra-logging-fluentd


export INFRA_LOGGING_FLUENTD_ES_IMAGE_NAME_LOCAL=$INFRA_LOGGING_FLUENTD_ES_NAMESPACE/$INFRA_LOGGING_FLUENTD_ES_IMAGE_NAME
export INFRA_LOGGING_FLUENTD_ES_IMAGE_NAME_REPO=$INFRA_LOGGING_FLUENTD_ES_NAMESPACE/$INFRA_LOGGING_FLUENTD_ES_IMAGE_NAME
#commenting out the old repo name since we're now pulling from docker hub.  Keeping it so we can switch back when we get a local repo set up.
#export INFRA_LOGGING_FLUENTD_ES_IMAGE_NAME_REPO=$ECR_REPO:$INFRA_LOGGING_FLUENTD_ES_IMAGE_NAME
